#!/usr/bin/env python
import sys
import os

def sys_exec(c):
    print(c)
    os.system(c)


pyexec, v = 'python', 3
if len(sys.argv) > 1:
    v = int(float(sys.argv[1]))
if v < 3:
    pyexec = 'python2.7'

sys_exec('rm -rf build')
sys_exec('cython cnn/*.pyx')
sys_exec('%s setup.py install --home=$HOME' % pyexec)

