#!/usr/bin/env python

"""
pyinstall <version> <home>

Examples:
pyinstall
pyinstall 2 ~/mydir
"""
import sys
import os

def sys_exec(c):
    print(c)
    os.system(c)

pkg = os.path.split(os.getcwd())[1]
pyexec, v = 'python', 3
home = os.environ.get('HOME')
if len(sys.argv) > 1:
    v = int(float(sys.argv[1]))
    if len(sys.argv) > 2:
        home = sys.argv[2]
if v < 3:
    pyexec = 'python2.7'

print('Clean installing package: %s' % pkg)
print('Home directory: %s' % home)
sys_exec('rm -rf build')
sys_exec('cython %s/*.pyx' % pkg)
sys_exec('%s setup.py install --home=%s' % (pyexec, home))

